# SwiftLint Configuration
# Install: brew install swiftlint
# Run: swiftlint

included:
  - Sources

excluded:
  - .build
  - .swiftpm
  - DerivedData

# Rules
disabled_rules:
  - trailing_comma
  - identifier_name

opt_in_rules:
  - empty_count
  - empty_string
  - force_unwrapping
  - implicitly_unwrapped_optional
  - modifier_order
  - multiline_parameters
  - vertical_whitespace_closing_braces
  - vertical_whitespace_opening_braces

# Rule configurations
line_length:
  warning: 120
  error: 150
  ignores_comments: true
  ignores_urls: true

type_body_length:
  warning: 300
  error: 400

file_length:
  warning: 500
  error: 1000

function_body_length:
  warning: 50
  error: 100

function_parameter_count:
  warning: 6
  error: 8

type_name:
  min_length: 3
  max_length: 50

nesting:
  type_level: 2
  function_level: 3

# Custom rules
custom_rules:
  no_print:
    name: "No Print Statements"
    regex: "\\bprint\\s*\\("
    message: "Use proper logging instead of print statements"
    severity: warning
    match_kinds:
      - identifier
